# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'YoungRepublic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoungRepublic
  pod 'FirebaseAnalytics'  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crash'
  pod 'Firebase/DynamicLinks'
  #pod 'Firebase/Performance'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  
  

  target 'YoungRepublicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YoungRepublic-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoungRepublic-tvOS

  target 'YoungRepublic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
